import {
  Home,
  Slots,
  Livecasino,
  Promotions,
  Vip,
  Search,
  Menu,
  Close,
  Back,
  Help,
  More,
  SmallArrow,
  AcCharge,
  AcDiscount,
  AcInvitefriend,
  AcSetting,
  User,
  AcAlarm,
  Info,
  Backtotop,
  Onlinesupport,
  Check,
  HcAboutbitcoin,
  HcInfo,
  HcLoyaltyClub,
  HcOrder,
  HcPayment,
  HcReward,
  HcTutorial,
  HcBrands,
  HcCustomer,
  HcLocalized,
  HcCommission,
  HcCapital,
  HcMail,
  HcTelegram,
  HcSkype,
  Loading,
  BtnNext,
  NextMonth,
  NextYear,
  PrevMonth,
  PrevYear,
  Cookies,
  Partner,
  Responsible,
  Terms,
  Privacy,
  Treasure,
  World,
} from "@/components/Ui/Icon";

import styles from "./index.less";
import copy from "copy-to-clipboard";
const Index = () => {
  const data = [
    { name: "Home", icon: <Home /> },
    { name: "Slots", icon: <Slots /> },
    { name: "Livecasino", icon: <Livecasino /> },
    { name: "Promotions", icon: <Promotions /> },
    { name: "Vip", icon: <Vip /> },
    { name: "Search", icon: <Search /> },
    { name: "Menu", icon: <Menu /> },
    { name: "Close", icon: <Close /> },
    { name: "Back", icon: <Back /> },
    { name: "Help", icon: <Help /> },
    { name: "More", icon: <More /> },
    { name: "SmallArrow", icon: <SmallArrow /> },
    { name: "AcCharge", icon: <AcCharge /> },
    { name: "AcDiscount", icon: <AcDiscount /> },
    { name: "AcInvitefriend", icon: <AcInvitefriend /> },
    { name: "AcSetting", icon: <AcSetting /> },
    { name: "User", icon: <User /> },
    { name: "AcAlarm", icon: <AcAlarm /> },
    { name: "Info", icon: <Info /> },
    { name: "Backtotop", icon: <Backtotop /> },
    { name: "Onlinesupport", icon: <Onlinesupport /> },
    { name: "Check", icon: <Check /> },
    { name: "HcAboutbitcoin", icon: <HcAboutbitcoin /> },
    { name: "HcInfo", icon: <HcInfo /> },
    { name: "HcLoyaltyClub", icon: <HcLoyaltyClub /> },
    { name: "HcOrder", icon: <HcOrder /> },
    { name: "HcPayment", icon: <HcPayment /> },
    { name: "HcReward", icon: <HcReward /> },
    { name: "HcTutorial", icon: <HcTutorial /> },
    { name: "HcBrands", icon: <HcBrands /> },
    { name: "HcCustomer", icon: <HcCustomer /> },
    { name: "HcLocalized", icon: <HcLocalized /> },
    { name: "HcCommission", icon: <HcCommission /> },
    { name: "HcCapital", icon: <HcCapital /> },
    { name: "HcMail", icon: <HcMail /> },
    { name: "HcTelegram", icon: <HcTelegram /> },
    { name: "HcSkype", icon: <HcSkype /> },
    { name: "Loading", icon: <Loading /> },
    { name: "BtnNext", icon: <BtnNext /> },
    { name: "NextMonth", icon: <NextMonth /> },
    { name: "NextYear", icon: <NextYear /> },
    { name: "PrevMonth", icon: <PrevMonth /> },
    { name: "PrevYear", icon: <PrevYear /> },
    { name: "Partner", icon: <Partner /> },
    { name: "Cookies", icon: <Cookies /> },
    { name: "Responsible", icon: <Responsible /> },
    { name: "Terms", icon: <Terms /> },
    { name: "Privacy", icon: <Privacy /> },
    { name: "Treasure", icon: <Treasure /> },
    { name: "World", icon: <World /> },
  ];
  return (
    <div className={styles.icon}>
      {data.map((item, index) => (
        <div
          key={index}
          onClick={() => {
            copy(`<${item.name} />`);
          }}>
          {item.icon}
        </div>
      ))}
    </div>
  );
};
export default Index;
